// <auto-generated />
using System;
using LeanAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeanAI.Infrastructure.Migrations
{
    [DbContext(typeof(LeanAIDbContext))]
    [Migration("20260510204522_Add_DailyIdealWeights_DailyActualWeights")]
    partial class Add_DailyIdealWeights_DailyActualWeights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.DailyActualWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DailyActualWeights");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.DailyIdealWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DailyIdealWeights");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartingWeightKg")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
