// <auto-generated />
using System;
using LeanAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeanAI.Infrastructure.Migrations
{
    [DbContext(typeof(LeanAIDbContext))]
    [Migration("20260516073949_Add_ActivityLogs")]
    partial class Add_ActivityLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("LeanAI.Domain.ActivityTracking.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CalendarFirstDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeminiModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.DailyActualWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DailyActualWeights");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.DailyIdealWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DailyIdealWeights");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalStartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartingWeightKg")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LeanAI.Domain.WeightManagement.Entities.WeeklyAverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageWeightKg")
                        .HasColumnType("REAL");

                    b.Property<string>("WeekStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart")
                        .IsUnique();

                    b.ToTable("WeeklyAverages");
                });
#pragma warning restore 612, 618
        }
    }
}
